# Generated by Django 5.2.5 on 2025-08-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='status',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('preventiva', 'Realizar Preventiva'), ('desligada', 'Desligada')], default='desligada', max_length=20),
        ),
    ]
