# Generated by Django 5.2.5 on 2025-08-14 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maquina_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacoes_por_email', models.BooleanField(default=True)),
                ('tema', models.CharField(default='Tema Claro', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
